enableInlineBuilds: true

nodeLinker: node-modules

npmPublishRegistry: "https://artifactory.pipeline.smartsheet.com/artifactory/api/npm/npm"

npmScopes:
  cuflink-test:
    npmRegistryServer: "https://artifactory.pipeline.smartsheet.com/artifactory/api/npm/npm"
  smartsheet:
    npmRegistryServer: "https://artifactory.pipeline.smartsheet.com/artifactory/api/npm/npm"
  smartsheet-forms:
    npmRegistryServer: "https://artifactory.pipeline.smartsheet.com/artifactory/api/npm/npm"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
